2025-03-12 13:23:04,615 INFO    MainThread:34763 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-12 13:23:04,616 INFO    MainThread:34763 [wandb_setup.py:_flush():67] Configure stats pid to 34763
2025-03-12 13:23:04,616 INFO    MainThread:34763 [wandb_setup.py:_flush():67] Loading settings from /home/lyngsberg/.config/wandb/settings
2025-03-12 13:23:04,616 INFO    MainThread:34763 [wandb_setup.py:_flush():67] Loading settings from /home/lyngsberg/fagproject/02466_project/wandb/settings
2025-03-12 13:23:04,616 INFO    MainThread:34763 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-12 13:23:04,616 INFO    MainThread:34763 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/lyngsberg/fagproject/02466_project/wandb/run-20250312_132304-o17q2gg4/logs/debug.log
2025-03-12 13:23:04,616 INFO    MainThread:34763 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/lyngsberg/fagproject/02466_project/wandb/run-20250312_132304-o17q2gg4/logs/debug-internal.log
2025-03-12 13:23:04,616 INFO    MainThread:34763 [wandb_init.py:init():761] calling init triggers
2025-03-12 13:23:04,616 INFO    MainThread:34763 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'BATCH_SIZE': 64, 'LEARNING_RATE': 0.001, 'EPOCHS': 3, 'SEED': 42, '_wandb': {}}
2025-03-12 13:23:04,616 INFO    MainThread:34763 [wandb_init.py:init():784] starting backend
2025-03-12 13:23:04,616 INFO    MainThread:34763 [wandb_init.py:init():788] sending inform_init request
2025-03-12 13:23:04,619 INFO    MainThread:34763 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-12 13:23:04,620 INFO    MainThread:34763 [wandb_init.py:init():798] backend started and connected
2025-03-12 13:23:04,621 INFO    MainThread:34763 [wandb_init.py:init():891] updated telemetry
2025-03-12 13:23:04,626 INFO    MainThread:34763 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-12 13:23:06,195 ERROR   MainThread:34763 [wandb_init.py:init():1478] error in wandb.init()
Traceback (most recent call last):
  File "/home/lyngsberg/miniconda3/envs/fagprojekt/lib/python3.13/site-packages/wandb/sdk/wandb_init.py", line 1468, in init
    return wi.init(run_settings, run_config)
           ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lyngsberg/miniconda3/envs/fagprojekt/lib/python3.13/site-packages/wandb/sdk/wandb_init.py", line 963, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 404: {"data":{"upsertBucket":null},"errors":[{"message":"entity Danmarks Tekniske Universitet - DTU not found during upsertBucket","path":["upsertBucket"]}]}
2025-03-12 13:23:07,198 INFO    MsgRouterThr:34763 [mailbox.py:close():129] Closing mailbox, abandoning 0 handles.
