2025-03-12 13:19:20,053 INFO    MainThread:33395 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-12 13:19:20,053 INFO    MainThread:33395 [wandb_setup.py:_flush():67] Configure stats pid to 33395
2025-03-12 13:19:20,053 INFO    MainThread:33395 [wandb_setup.py:_flush():67] Loading settings from /home/lyngsberg/.config/wandb/settings
2025-03-12 13:19:20,053 INFO    MainThread:33395 [wandb_setup.py:_flush():67] Loading settings from /home/lyngsberg/fagproject/02466_project/wandb/settings
2025-03-12 13:19:20,053 INFO    MainThread:33395 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-12 13:19:20,053 INFO    MainThread:33395 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/lyngsberg/fagproject/02466_project/wandb/run-20250312_131920-qtw98lzp/logs/debug.log
2025-03-12 13:19:20,053 INFO    MainThread:33395 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/lyngsberg/fagproject/02466_project/wandb/run-20250312_131920-qtw98lzp/logs/debug-internal.log
2025-03-12 13:19:20,053 INFO    MainThread:33395 [wandb_init.py:init():761] calling init triggers
2025-03-12 13:19:20,053 INFO    MainThread:33395 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'BATCH_SIZE': 64, 'LEARNING_RATE': 0.001, 'EPOCHS': 3, 'SEED': 42, '_wandb': {}}
2025-03-12 13:19:20,053 INFO    MainThread:33395 [wandb_init.py:init():784] starting backend
2025-03-12 13:19:20,053 INFO    MainThread:33395 [wandb_init.py:init():788] sending inform_init request
2025-03-12 13:19:20,060 INFO    MainThread:33395 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-12 13:19:20,060 INFO    MainThread:33395 [wandb_init.py:init():798] backend started and connected
2025-03-12 13:19:20,061 INFO    MainThread:33395 [wandb_init.py:init():891] updated telemetry
2025-03-12 13:19:20,066 INFO    MainThread:33395 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-12 13:19:21,751 ERROR   MainThread:33395 [wandb_init.py:init():1478] error in wandb.init()
Traceback (most recent call last):
  File "/home/lyngsberg/miniconda3/envs/fagprojekt/lib/python3.13/site-packages/wandb/sdk/wandb_init.py", line 1468, in init
    return wi.init(run_settings, run_config)
           ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lyngsberg/miniconda3/envs/fagprojekt/lib/python3.13/site-packages/wandb/sdk/wandb_init.py", line 963, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403: {"data":{"upsertBucket":null},"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}]}
2025-03-12 13:19:22,752 INFO    MsgRouterThr:33395 [mailbox.py:close():129] Closing mailbox, abandoning 0 handles.
